### ISSUE TITLE
Panic when viewing Monitored Apps on Linux

### ISSUE THREAD

**Issue by inventor96** [wakatime/desktop-wakatime#41]
On Linux Mint 21.3, the process panics when I attempt to view the Monitored Apps from the context menu of the tray icon. I'm starting the app from the terminal. Here's the relevant parts of my terminal session while attempting to get some more details to share:

```
$ ./wakatime-linux-x86_64.AppImage 
[WakaTime][DEBUG] Failed to read file: /home/caleb/.config/WakaTime/desktop-wakatime.cfg. Error: Error: ENOENT: no such file or directory, open '/home/caleb/.config/WakaTime/desktop-wakatime.cfg'
[WakaTime][DEBUG] Electron's autoUpdater does not support the 'linux' platform. Ref: https://www.electronjs.org/docs/latest/api/auto-updater#platform-notices
[WakaTime][DEBUG] Starting WakaTime
[WakaTime][DEBUG] Registered as login item
[WakaTime][DEBUG] Fetching code time: /home/caleb/.wakatime/wakatime-cli-linux-amd64 --today,--today-hide-categories,true,--plugin,linux-wakatime/0.5.0
[WakaTime][DEBUG] App changed from nil to Gnome-terminal
[WakaTime][DEBUG] Latest wakatime-cli release: v1.102.1
[WakaTime][DEBUG] App changed from Gnome-terminal to desktop-wakatime
[WakaTime][DEBUG] App changed from desktop-wakatime to Gnome-terminal
[WakaTime][DEBUG] App changed from Gnome-terminal to desktop-wakatime
thread '<unnamed>' panicked at x-win-rs/src/linux/api/common_api.rs:43:65:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

$ ./wakatime-linux-x86_64.AppImage 
[WakaTime][DEBUG] Electron's autoUpdater does not support the 'linux' platform. Ref: https://www.electronjs.org/docs/latest/api/auto-updater#platform-notices
[WakaTime][DEBUG] Starting WakaTime
[WakaTime][DEBUG] Registered as login item
[WakaTime][DEBUG] Fetching code time: /home/caleb/.wakatime/wakatime-cli-linux-amd64 --today,--today-hide-categories,true,--plugin,linux-wakatime/0.5.0
[WakaTime][DEBUG] App changed from nil to Gnome-terminal
[WakaTime][DEBUG] Skip checking for wakatime-cli updates because recently checked 4 minutes ago
[WakaTime][DEBUG] App changed from Gnome-terminal to desktop-wakatime
thread '<unnamed>' panicked at x-win-rs/src/linux/api/common_api.rs:43:65:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

$ export RUST_BACKTRACE=1

$ ./wakatime-linux-x86_64.AppImage 
[WakaTime][DEBUG] Electron's autoUpdater does not support the 'linux' platform. Ref: https://www.electronjs.org/docs/latest/api/auto-updater#platform-notices
[WakaTime][DEBUG] Starting WakaTime
[WakaTime][DEBUG] Registered as login item
[WakaTime][DEBUG] Fetching code time: /home/caleb/.wakatime/wakatime-cli-linux-amd64 --today,--today-hide-categories,true,--plugin,linux-wakatime/0.5.0
[WakaTime][DEBUG] App changed from nil to Gnome-terminal
[WakaTime][DEBUG] Skip checking for wakatime-cli updates because recently checked 5 minutes ago
[WakaTime][DEBUG] App changed from Gnome-terminal to desktop-wakatime
thread '<unnamed>' panicked at x-win-rs/src/linux/api/common_api.rs:43:65:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

$ export RUST_BACKTRACE=full

$ ./wakatime-linux-x86_64.AppImage 
[WakaTime][DEBUG] Electron's autoUpdater does not support the 'linux' platform. Ref: https://www.electronjs.org/docs/latest/api/auto-updater#platform-notices
[WakaTime][DEBUG] Starting WakaTime
[WakaTime][DEBUG] Registered as login item
[WakaTime][DEBUG] Fetching code time: /home/caleb/.wakatime/wakatime-cli-linux-amd64 --today,--today-hide-categories,true,--plugin,linux-wakatime/0.5.0
[WakaTime][DEBUG] App changed from nil to Gnome-terminal
[WakaTime][DEBUG] Skip checking for wakatime-cli updates because recently checked 5 minutes ago
[WakaTime][DEBUG] App changed from Gnome-terminal to desktop-wakatime
thread '<unnamed>' panicked at x-win-rs/src/linux/api/common_api.rs:43:65:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x7f963cca8df1 - <unknown>
   1:     0x7f963cc4c7cb - <unknown>
   2:     0x7f963cc7cf42 - <unknown>
   3:     0x7f963ccae1e9 - <unknown>
   4:     0x7f963ccad9d6 - <unknown>
   5:     0x7f963ccaeee1 - <unknown>
   6:     0x7f963ccae552 - <unknown>
   7:     0x7f963ccae4a9 - <unknown>
   8:     0x7f963ccae496 - <unknown>
   9:     0x7f963cc3e282 - <unknown>
  10:     0x7f963cc3e745 - <unknown>
  11:     0x7f963ccea9af - <unknown>
  12:     0x7f963ccdd96a - <unknown>
  13:     0x7f963ccf8326 - <unknown>
  14:     0x5642fdf2e2e8 - <unknown>
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

**Comment by Pegoku** [comment]
I have the same error

**Comment by weastur** [comment]
+1
Sway, Fedora 41
